### ISSUE TITLE
[question] What are JP1, R1, R2, P1, and P2 for?

### ISSUE THREAD

**Issue by repercussion** [tamanishi/Pinky3#2]
JP1 - What is this jumper for?

R1 and R2 - I assume these are for resistors for underglow?

P1 and P2 - Haven't the foggiest.

**Comment by tamanishi** [comment]
[image: reset_switch.jpg]
Hi.

Sorry for the late reply.

> I've bought a few PCBs and necessary parts, but I'm wondering if you
might help me find the appropriate resest switches.

I'm using reset switch like this. (see attached.

> JP1 - What is this jumper for?

> R1 and R2 - I assume these are for resistors for underglow?

> P1 and P2 - Haven't the foggiest.
JP1 is for switching the communication protocol for left and right between
I2C or serial.
If JP1 is closed, the communication is on serial protocol.
If JP1 is opened, the communication is on I2C protocol.
and R1, R2, P1 and P2 are for I2C protocol.
But I don't test I2C protocol physically yet.

Serial protocol is OK for me for now.

I hope this helps you.

--
Masayuki Sunahara

**Comment by repercussion** [comment]
Thank you very much for the information!

The image of the reset switch didn't make it from attachment to GitHub.

**Comment by tamanishi** [comment]
Oops.

please try this.

https://imgur.com/gallery/vSJpcNz

--
Masayuki Sunahara

**Comment by repercussion** [comment]
Thanks! 

![Reset switch](https://i.imgur.com/EkxfLI0.jpg)
